### ISSUE TITLE
obs3dian 도입에 관련해서

### ISSUE THREAD

**Issue by thinkjin99** [gdsc-ssu/CSocrates#64]
안녕하세요
개인적으로 이젠 정말 이미지 파일 관리가 혼잡해졌고 이미지가 계속해서 쌓여나가면서 레포 자체를 클론하거나
옮기는 행위가 생각보다 오버헤드가 커졌습니다.

이에 따라서 이미지를 [옵3디언](https://github.com/thinkjin99/obs3dian)을 사용해서 업로드하거나
액션에 이를 달아 커밋과 동시에 옵3디언이 동작하는 파이프라인을 구축하고 싶은데요.

> 이미지 자체를 애초에 외부 링크로 업로드해도 이런 문제는 해결할 수 있습니다만, 
외부링크는 저희가 관리할 수 있는 영역이 아니다 보니 유실 가능성이 존재해 가능한 지양하고 싶습니다.

이와 관련해서 의견 부탁드립니다.

**Comment by thinkjin99** [comment]
추가적으로 옵3디언 사용한다면 누구 계정의 S3에 업로드 할 것인지도 애기해보면 좋을 듯 합니다~

**Comment by halfmoon-mind** [comment]
정말 훌륭한 생각인데요
그렇다면 누구의 s3 버킷로 올리느냐가 관건일 것 같은데
누구의 버킷으로 하는게 좋을까요?
아무래도 이미지 파일이다보니 용량이 좀 커질 것 같은 느낌입니다.

**Comment by thinkjin99** [comment]
> 정말 훌륭한 생각인데요 그렇다면 누구의 s3 버킷로 올리느냐가 관건일 것 같은데 누구의 버킷으로 하는게 좋을까요? 아무래도 이미지 파일이다보니 용량이 좀 커질 것 같은 느낌입니다.

절대 권력 선착순으로 1분에게 드립니다.

**Comment by halfmoon-mind** [comment]
s3 드렸습니다

**Comment by thinkjin99** [comment]
상현님 S3계정 통해서 진행하기로 했습니다. 워크 플로우는 다음과 같이 진행될듯 합니다.
* 이미지 파일 + 마크다운 파일을 푸시
* 액션 서버 내부에서 obs3dian 동작
* 동작 후 변경사항 자동 커밋

**Comment by halfmoon-mind** [comment]
main 브랜치에 머지되면, 자동으로 업로드 되도록 설정되어 해당 Issue는 닫도록 하겠습니다 :)
